# Generated by Django 4.2.11 on 2024-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('contenido', models.TextField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(upload_to='actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=500)),
                ('git_hub', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_perfil', models.ImageField(upload_to='perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('progreso', models.PositiveIntegerField()),
            ],
        ),
    ]
