# Generated by Django 4.2.11 on 2024-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_actividad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
        migrations.AddField(
            model_name='datos',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='contenido',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datos',
            name='git_hub',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
