# Generated by Django 4.2.11 on 2024-04-10 22:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_datos_cv_datos_linkedin_alter_actividad_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
