# Generated by Django 4.2.11 on 2024-04-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_alter_actividad_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
