# Generated by Django 4.2.11 on 2024-04-11 23:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
