# Generated by Django 4.2.11 on 2024-04-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_remove_actividad_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='link',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='link_articulo',
            new_name='git_hub',
        ),
        migrations.AddField(
            model_name='actividad',
            name='web',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
