# Generated by Django 4.2.11 on 2024-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_rename_link_actividad_articulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default='False')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('asunto', models.CharField(blank=True, max_length=300, null=True)),
                ('mensaje', models.TextField(blank=True, max_length=3000, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
