# Generated by Django 4.2.11 on 2025-11-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo-profile'),
        ),
    ]
