# Generated by Django 4.2.11 on 2026-03-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_datos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='sub_titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tecnoloias',
            field=models.ManyToManyField(blank=True, related_name='tecnologias', to='profile.tecnologia'),
        ),
    ]
