# Generated by Django 4.2.11 on 2026-03-15 21:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_actividad_sub_titulo_actividad_tecnoloias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='sub_titulo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
