# Generated by Django 4.2.11 on 2024-03-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
        migrations.AlterModelOptions(
            name='datos',
            options={'verbose_name': 'datos', 'verbose_name_plural': 'datos'},
        ),
        migrations.AlterField(
            model_name='datos',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
